### ISSUE TITLE
Prepare Jakarta RESTful Web Services project for Jakarta EE 8 Release

### ISSUE THREAD

**Issue by spericas** [eclipse-ee4j/jaxrs-api#776]
## Tasks

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Create a PR to jakartaee/specifications repository
- [x] Update the Jakarta EE API jar by submitting a PR to the [jakartaee-api](https://github.com/eclipse-ee4j/jakartaee-api) project

Some changes are required for the Jakarta EE 8 release in our Javadocs and top-level files as described here:

https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release

**Comment by ivargrimstad** [comment]
Thanks for starting this @spericas !
Here are some detailed instructions..

### Instructions

- [ ] Update text files
- [ ] Generate "boilerplate" specification project
- [ ] Make a staging release
- [ ] Generate Stand-alone TCK test results
- [ ] Submit tests for ballot
- [ ] Release to Maven Central

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by spericas** [comment]
Related to #775

**Comment by spericas** [comment]
I will be submitting a PR shortly with some changes to drop references to "JAX-RS" from the Javadocs. Most of these references are unnecessary and can be replaced by "This API" or simply inferred by the context. See bullet 1.2 in how-to above.

**Comment by m0mus** [comment]
Staging release: https://oss.sonatype.org/content/repositories/staging/jakarta/ws/rs/jakarta.ws.rs-api/2.1.6/

**Comment by m0mus** [comment]
jakartaee/specifications PRs:
https://github.com/jakartaee/specifications/pull/7
https://github.com/jakartaee/specifications/pull/8

**Comment by mkarg** [comment]
IIUC then Jakarta EE 8 is released including JAX-RS 2.1.6, so can we close this issue or is there still work to do?

**Comment by spericas** [comment]
I think so. Closing it now.
